# -*- coding: utf-8 -*-
"""OOPs_Aggregation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15sYX_YMojizjyH3oIvbcjIxogDs_FVvz
"""

class Customer:
  def __init__(self,name,gender,address):
    self.name = name
    self.gender = gender
    self.address = address

  def print_address(self):
    print(self.name,self.gender,self.address.get_city(),self.address.pin,self.address.state)

  def edit_profile(self,new_name, new_gender, new_city, new_pin, new_state):
    self.name = new_name
    self.gender = new_gender
    self.address.edit_address(new_city,new_pin,new_state)

class Address:
  def __init__(self,city,pin,state):
    self.__city = city
    self.pin = pin
    self.state = state

  def get_city(self):
    return self.__city

  def edit_address(self,new_city,new_pin,new_state):
    self.__city = new_city
    self.pin = new_pin
    self.state = new_state
add1 = Address('mumbai',400709,'maharashtra')
cust = Customer('tejas','male',add1)
cust.print_address()
cust.edit_profile('Ram','male','jaipur',683234,'rajasthan')

cust.print_address()

