# -*- coding: utf-8 -*-
"""Personal_Finance_Manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A3zg_8DtSiAWefVuEnuwuAST_yxSKBbx
"""

class Transaction:
  def __init__(self,amount, category, date, description):
    #pass
    self.amount = amount
    self.category = category
    self.date = date
    self.description = description

  def __str__(self):
    return f"{self.date} | {self.category} | Rs.{self.amount} | {self.description}"

class Income(Transaction):
  def __init__(self,amount,category,date,description):
    super().__init__(amount,category,date,description)

class Expense(Transaction):
  def __init__(self,amount,category,date,description):
    super().__init__(amount,category,date,description)

class User:
  def __init__(self,username,password):
    self.username = username
    self.password = password
    self.incomes =[]
    self.expenses =[]

  def add_income(self,amount,category,date,description):
    income = Income(amount,category,date,description)
    self.incomes.append(income)

  def add_expense(self,amount,category,date,description):
    expense=Expense(amount,category,date,description)
    self.expenses.append(expense)

  def show_all_transaction(self):
    print(f"\nIncomes for {self.username}: ")
    for income in self.incomes:
      print(income)

    print(f"\nExpenses for {self.username}: ")
    for expense in self.expenses:
      print(expense)

  def total_income(self):
    tincome = sum(income.amount for income in self.incomes)
    print(f"Total Income: {tincome}")

  def total_expense(self):
    texpense = sum(expense.amount for expense in self.expenses)
    print(f"Total Expense: {texpense}")

  def total_balance(self):
    tincome = sum(income.amount for income in self.incomes)
    texpense = sum(expense.amount for expense in self.expenses)
    balance = tincome-texpenseac
    print(f"Total Balance: {balance}")

def main():
  print("Welcome to personal Finance manager")

  username = input("Enter username: ")
  password = input("Enter Password: ")

  user = User(username,password)
  while True:
    print("\n📋 Choose an option:")
    print("1. Add Income")
    print("2. Add Expense")
    print("3. Show All Transactions")
    print("4. Total Income")
    print("5. Total Expense")
    print("6. Balance")
    print("7. Exit")


    choice = int(input("Enter your Choice(1-4): "))

    if choice==1:
      amount = float(input("Enter income amount: "))
      category = input("Enter income category: ")
      date = input("Enter date (YYYY-MM-DD): ")
      description = input("Enter description: ")

      user.add_income(amount,category,date,description)
      print("Income added")

    elif choice==2:
      amount = float(input("Enter income amount: "))
      category = input("Enter income category: ")
      date = input("Enter date (YYYY-MM-DD): ")
      description = input("Enter description: ")

      user.add_expense(amount,category,date,description)
      print("Expense Added!!")

    elif choice == 3:
      user.show_all_transaction()

    elif choice==4:
      user.total_income()

    elif choice==5:
      user.total_expense()
    elif choice==6:
      user.total_balance()
    elif choice==7:
      print("Goodbye!")
      break

    else:
      print("Invalid choice, try again")

main()